/* 퍼즐에 쓸 수 있는 사진 목록.
   단색 영역이 큰 사진은 조각에 단서가 없어서 맞출 수가 없다.
   조각마다 무늬가 얼마나 있는지 재서 걸러낸 결과다. */
(function () {
  'use strict';
  window.PuzzleOk = {
    'animal_camel': 1,
    'animal_deer': 1,
    'animal_hedgehog': 1,
    'animal_kangaroo': 1,
    'animal_leopard': 1,
    'animal_orangutan': 1,
    'animal_otter': 1,
    'animal_panda': 1,
    'animal_raccoon': 1,
    'animal_rhino': 1,
    'animal_sloth': 1,
    'animal_zebra': 1,
    'car_ambulance': 1,
    'car_bike': 1,
    'car_bus': 1,
    'car_jeep': 1,
    'car_moto': 1,
    'car_police': 1,
    'car_racecar': 1,
    'car_sedan': 1,
    'car_taxi': 1,
    'car_train': 1,
    'car_van': 1,
    'sea_clownfish': 1,
    'sea_crab': 1,
    'sea_lobster': 1,
    'sea_seal': 1,
    'sea_starfish': 1,
    'special_combine': 1,
    'special_dump': 1,
    'special_excavator': 1,
    'special_roller': 1,
    'special_tiller': 1,
    'special_tractor': 1,
    'train_busansubway': 1,
    'train_electricloco': 1,
    'train_goldtrain': 1,
    'train_itxcheongchun': 1,
    'train_itxmaeum': 1,
    'train_itxsaemaeul': 1,
    'train_ktx': 1,
    'train_ktxeum': 1,
    'train_ktxsancheon': 1,
    'train_lightrail': 1,
    'train_monorail': 1,
    'train_mugunghwa': 1,
    'train_nuriro': 1,
    'train_saemaeul': 1,
    'train_seatrain': 1,
    'train_steam': 1,
    'train_subway': 1,
    'train_tram': 1,
    'train_valleytrain': 1,
  };
})();
